// MAPIWrapper.idl : IDL source for MAPIWrapper
//

// This file will be processed by the MIDL tool to
// produce the type library (MAPIWrapper.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
interface IMapiTableWrp;

//************************************************************************
[
	object,
	uuid(92BCCF25-803C-4312-8959-AA586612A218),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMapiFolderWrp : IDispatch{
	[id(1)] HRESULT GetAllSubFolders([in] VARIANT mapiObject, [out,retval] IMapiTableWrp ** ppSubFolders);
	[id(2)] HRESULT MoveTo([in] VARIANT session);

};

//************************************************************************

[
	object,
	uuid(2F5010CC-B8D4-4330-89DB-D36AC4F1237A),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMapiTableWrp : IDispatch{
	[id(1)] HRESULT GetNextItems([in] ULONG rowCount,[out] VARIANT *buffer);
	[propget, id(2)] HRESULT Count([out, retval] ULONG* pVal);
	[id(3)] HRESULT Setup([in] VARIANT propTags);
};

//************************************************************************

[
	uuid(24043FC4-3E9C-48BD-9563-3C76960C2073),
	version(1.0),
]
library MAPIWrapperLib
{
	typedef
	[
		helpstring("Mapi property tags")
	]
	enum MapiPropTags
	{
		DisplayName = 0x3001001F,
		ContentCount  = 0x36020003,
		AssociatedContentCount = 0x36170003,
		HasSubfolders = 0x360A000B,
		ParentSourceKey = 0x65E10102,
	} MapiPropTags;

	importlib("stdole2.tlb");
	[
		uuid(D88741BD-32E9-4747-8664-87218C302B87)		
	]
	dispinterface _IMapiFolderWrpEvents
	{
		properties:
		methods:
	};
	[
		uuid(02AE975F-6795-463E-BED8-6FFC1B74D958)		
	]
	coclass MapiFolderWrp
	{
		[default] interface IMapiFolderWrp;
		[default, source] dispinterface _IMapiFolderWrpEvents;
	};
	[
		uuid(8CD1E521-F1E1-49A2-A31B-89E410B7BDBA)		
	]
	coclass MapiTable
	{
		[default] interface IMapiTableWrp;
	};
};

